[package]
name = "sock"
version = "0.1.0"
authors = ["Andrew Danger Lyon <orthecreedence@gmail.com>"]

[dependencies]
cwrap = { path = "../cwrap" }
fern = "0.5.5"
log = "0.4.1"
time = "0.1.35"
tungstenite = "0.10.1"

